# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13cVSizNe4Zt1hLwb7BJymFk907N5mFts
"""

from flask import Flask, request, jsonify
import tensorflow as tf

# Load the saved model
model = tf.keras.models.load_model('model.h5')

# Create the Flask app
app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    # Get the input data from the request
    data = request.json
    uraian = data['uraian']

    # Perform any necessary preprocessing on the input data
    # ...

    # Make the prediction using the loaded model
    prediction = model.predict([preprocessed_data])

    # Perform any necessary postprocessing on the prediction
    # ...

    # Create a response dictionary
    response = {'prediction': prediction}

    # Return the response as JSON
    return jsonify(response)

    if __name__ == '__main__':
    app.run()